### ISSUE TITLE
Clarity on the README.

### ISSUE THREAD

**Issue by AbstractUmbra** [openai/gpt-discord-bot#10]
Hi there.

The README currently states that [you don't accept PRs](https://github.com/openai/gpt-discord-bot/blob/90fce7259aea3faefef92054a684c94c7c66bff5/README.md?plain=1#L5) yet I see one fix PR was accepted.

Can you clarify if PRs are accepted or not? 
I would like to improve the codebase as I can see a few places where it can be improved, especially if this is a template repository.

**Comment by YufeiG** [comment]
It was a bug that I needed to fix and they already fixed it. If you see bugs please file a ticket and I can fix it.
