### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed.

### ISSUE THREAD

**Issue by falconzzz00** [openai/gpt-discord-bot#16]
It happens after I ran this command

pip install -r requirements.txt
python -m src.main

How to fix it?

**Comment by YufeiG** [comment]
make sure youre bot token is the right token.

**Comment by falconzzz00** [comment]
I tried to refresh the token and do it again but still the same problem.
Here are the full logs.

Requirement already satisfied: discord.py==2.1.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: python-dotenv==0.21.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 2)) (0.21.1)
Requirement already satisfied: openai==0.25.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: PyYAML==6.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 4)) (6.0)
Requirement already satisfied: dacite==1.6.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 5)) (1.6.0)
Requirement already satisfied: aiohttp<4,>=3.7.4 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from discord.py==2.1.*->-r requirements.txt (line 1)) (3.8.3)
Requirement already satisfied: requests>=2.20 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: tqdm in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (4.64.1)
Requirement already satisfied: numpy in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.24.1)
Requirement already satisfied: typing-extensions in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (4.4.0)
Requirement already satisfied: pandas>=1.2.3 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: openpyxl>=3.0.7 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (3.0.10)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.5.2.230105)
Requirement already satisfied: frozenlist>=1.1.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(6.0.4)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(2.1.1)
Requirement already satisfied: attrs>=17.3.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(22.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(4.0.2)
Requirement already satisfied: et-xmlfile in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openpyxl>=3.0.7->openai==0.25.*->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas>=1.2.3->openai==0.25.*->-r requirements.txt (line 3))
(2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas>=1.2.3->openai==0.25.*->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: types-pytz>=2022.1.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas-stubs>=1.1.0.11->openai==0.25.*->-r requirements.txt (line 3))
(2022.7.1.0)
Requirement already satisfied: idna<4,>=2.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3))
(1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3))
(2022.12.7)
Requirement already satisfied: colorama in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from tqdm->openai==0.25.*->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: six>=1.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from python-dateutil>=2.8.1->pandas>=1.2.3->openai==0.25.*->-r
requirements.txt (line 3)) (1.16.0)
[2023-01-22 16:34:54,157] [client.py:263] PyNaCl is not installed, voice
will NOT be supported
2023-01-22 16:34:54 INFO     discord.client logging in using static token
[2023-01-22 16:34:54,158] [client.py:571] logging in using static token
Traceback (most recent call last):
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 801, in static_login
    data = await self.request(Route('GET', ***@***.***'))
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401:
Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py",
line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py",
line 86, in _run_code
    exec(code, run_globals)
  File "D:\Download\gpt-discord-bot-main\gpt-discord-bot-main\src\main.py",
line 267, in <module>
    client.run(DISCORD_BOT_TOKEN)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 828, in run
    asyncio.run(runner())
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py",
line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py",
line 649, in run_until_complete
    return future.result()
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 817, in runner
    await self.start(token, reconnect=reconnect)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 745, in start
    await self.login(token)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 580, in login
    data = await self.http.static_login(token)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
PS D:\Download\gpt-discord-bot-main\gpt-discord-bot-main> pip install -r
requirements.txt
>> python -m src.main
Requirement already satisfied: discord.py==2.1.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: python-dotenv==0.21.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 2)) (0.21.1)
Requirement already satisfied: openai==0.25.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: PyYAML==6.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 4)) (6.0)
Requirement already satisfied: dacite==1.6.* in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from -r requirements.txt (line 5)) (1.6.0)
Requirement already satisfied: aiohttp<4,>=3.7.4 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from discord.py==2.1.*->-r requirements.txt (line 1)) (3.8.3)
Requirement already satisfied: typing-extensions in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (4.4.0)
Requirement already satisfied: openpyxl>=3.0.7 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (3.0.10)
Requirement already satisfied: tqdm in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (4.64.1)
Requirement already satisfied: pandas>=1.2.3 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.5.2.230105)
Requirement already satisfied: numpy in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (1.24.1)
Requirement already satisfied: requests>=2.20 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openai==0.25.*->-r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: aiosignal>=1.1.2 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(2.1.1)
Requirement already satisfied: attrs>=17.3.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(22.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(1.3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from aiohttp<4,>=3.7.4->discord.py==2.1.*->-r requirements.txt (line 1))
(6.0.4)
Requirement already satisfied: et-xmlfile in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from openpyxl>=3.0.7->openai==0.25.*->-r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas>=1.2.3->openai==0.25.*->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas>=1.2.3->openai==0.25.*->-r requirements.txt (line 3))
(2022.7.1)
Requirement already satisfied: types-pytz>=2022.1.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from pandas-stubs>=1.1.0.11->openai==0.25.*->-r requirements.txt (line 3))
(2022.7.1.0)
Requirement already satisfied: idna<4,>=2.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3))
(2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from requests>=2.20->openai==0.25.*->-r requirements.txt (line 3))
(1.26.14)
Requirement already satisfied: colorama in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from tqdm->openai==0.25.*->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: six>=1.5 in
c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
(from python-dateutil>=2.8.1->pandas>=1.2.3->openai==0.25.*->-r
requirements.txt (line 3)) (1.16.0)
[2023-01-22 16:36:25,637] [client.py:263] PyNaCl is not installed, voice
will NOT be supported
2023-01-22 16:36:25 INFO     discord.client logging in using static token
[2023-01-22 16:36:25,638] [client.py:571] logging in using static token
Traceback (most recent call last):
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 801, in static_login
    data = await self.request(Route('GET', ***@***.***'))
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401:
Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py",
line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py",
line 86, in _run_code
    exec(code, run_globals)
  File "D:\Download\gpt-discord-bot-main\gpt-discord-bot-main\src\main.py",
line 267, in <module>
    client.run(DISCORD_BOT_TOKEN)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 828, in run
    asyncio.run(runner())
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py",
line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py",
line 649, in run_until_complete
    return future.result()
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 817, in runner
    await self.start(token, reconnect=reconnect)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 745, in start
    await self.login(token)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py",
line 580, in login
    data = await self.http.static_login(token)
  File
"C:\Users\Prince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py",
line 805, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
