### ISSUE TITLE
Requirements in README.md

### ISSUE THREAD

**Issue by Veylkh** [openai/gpt-discord-bot#2]
Python 3.9 is required for `list` to work. Otherwise, it has to be changed to `List`, which has to be imported from `typing`. If not, a `type not subscriptable` TraceBack is given.

**Comment by YufeiG** [comment]
Thank you, I will change to List

**Comment by Veylkh** [comment]
I've already got the working code ready on my end so I could make a PR quite easily.

**Comment by YufeiG** [comment]
closed with https://github.com/openai/gpt-discord-bot/pull/6
