### ISSUE TITLE
How do I remove the moderation

### ISSUE THREAD

**Issue by funxpy** [openai/gpt-discord-bot#21]
Title

**Comment by funxpy** [comment]
How do I also make it not use threads, and instead just respond to a prefix like "AI, (message)"

**Comment by OsbornVentures** [comment]
For no threads.

```
response = '> **' + user_message + '** - <@' + \
            str(message.user.id) + '>\n\n'
        response = f"**{message.user.display_name}** said *{user_message}*. {await responses.handle_response(user_message)}"
```

**Comment by funxpy** [comment]
Where do I put this? Do I remove the threads code?

**Comment by YufeiG** [comment]
For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757). Your question seems like a general coding inquiry, please ask in API Discussions and others will help you!
