### ISSUE TITLE
Personalizing the config.yaml

### ISSUE THREAD

**Issue by tagraf** [openai/gpt-discord-bot#29]
Can we create 5 separate personalities with such filename,
config.yaml.discorduser
config.yaml.two
config.yaml.three
config.yaml.four
config.yaml.nochange
---
I can't think of such personalities right now but I don't like the idea when people are going to use this and learn that by default, it's the "discord regular user" -- it's best to open the varieties of personality and allow us to quickly rename any selected file to 'config.yaml' without taxing my creativity to change how the dialogues should go.

**Comment by YufeiG** [comment]
This repo is not taking feature requests, you can talk about potential features in [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757). Feel free to fork the repo and add your own config.yaml!

Having a neutral default is good though, I will consider that.
