### ISSUE TITLE
I don't get it with the 7th step

### ISSUE THREAD

**Issue by Alfred-PictoCube** [openai/gpt-discord-bot#30]
Hi, like the little, i'm stuck with the 7th step, I installed the Open python library and discord.py but when i try the command "pip install -r + each of the requirements" i get "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'discord.py==2.1.*'
". 
Do i have to create a venv? if so i did it following https://discordpy.readthedocs.io/en/stable/intro.html, however i can't pass through this. Any help  with more explicit steps would be very appreciated.
Thanks!!

**Comment by Hemanth-2002** [comment]
Make sure u have the right python version. discord.py is only compatible with py 3.8, 3.9, 3.10

**Comment by Alfred-PictoCube** [comment]
I'm on Python 3.9 :/

**Comment by Alfred-PictoCube** [comment]
Ok i got it, i'm dumb, Thanks for trying to help.
