### ISSUE TITLE
I need help in deploying the bot

### ISSUE THREAD

**Issue by Hemanth-2002** [openai/gpt-discord-bot#31]
I tried deploying using render but for some reason its failing. (The build is successfull)

**Comment by rivailruiz** [comment]
@Hemanth-2002 Show me more information, maybe I can help you.

**Comment by YufeiG** [comment]
For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757)
