### ISSUE TITLE
Don't know why I'm getting this error 

### ISSUE THREAD

**Issue by Amalbro07** [openai/gpt-discord-bot#37]
![Screenshot_2023-02-03-18-21-55-30_dce875ef40efa4e902b2719365b6f678](https://user-images.githubusercontent.com/124343610/216640310-69788537-fe99-43e1-aee3-79ad5c707930.jpg)

**Comment by Amalbro07** [comment]
Now it's openai_api_key

**Comment by YufeiG** [comment]
For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757)

(Did you set that env variable?)

**Comment by 4mlsx** [comment]
Yes
