### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 4mlsx** [openai/gpt-discord-bot#38]
![Screenshot_2023-02-04-19-26-19-19_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/124343610/216771615-8a7fa23d-87bc-4c5e-b484-9f83d7e1d636.jpg)

Can you please help me with this error

**Comment by Veylkh** [comment]
You can use the template: https://github.com/openai/gpt-discord-bot/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by 4mlsx** [comment]
Huh i don't understand

**Comment by Veylkh** [comment]
The template helps the maintainer of the repository understand precisely the issue you're having.

**Comment by NeauraNightsong** [comment]
![Untitled](https://user-images.githubusercontent.com/124760089/217440798-756eb86c-889c-4259-939e-0ef1037e68d5.png)
I am experiencing the same issue, would love to know what I'm doing wrong! :)

**Comment by 4mlsx** [comment]
> ![Untitled](https://user-images.githubusercontent.com/124760089/217440798-756eb86c-889c-4259-939e-0ef1037e68d5.png)
> I am experiencing the same issue, would love to know what I'm doing wrong! :)

I don't know what to do

**Comment by YufeiG** [comment]
are you all using python 3.10+ ?

**Comment by YufeiG** [comment]
please post on the discord (see readme) for direct help

**Comment by YufeiG** [comment]
try top of main

**Comment by YufeiG** [comment]
followup here, the command you want to run in the terminal is "python -m src.main"
