### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by eighttran** [openai/gpt-discord-bot#40]
![image](https://user-images.githubusercontent.com/124460483/216786954-835e1cf0-80bc-476d-ac07-0cee4554b0ef.png)
i have followed the steps, tried resetting token many times. Is there any way to fix this error? Thanks

**Comment by AnthraxBPLLC** [comment]
i got the same issue with this guy

**Comment by YufeiG** [comment]
please post on the discord for help requests. you are using the wrong token for the discord bot. make sure you have created a bot and used its token https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
