### ISSUE TITLE
No Module named 'src'

### ISSUE THREAD

**Issue by NeauraNightsong** [openai/gpt-discord-bot#41]
Hey I was trying to set this up but after following all the instructions listed, I am not getting any results, just this error. I'm pretty new at this, so I would love if someone can tell me what I might of done wrong or be missing.

![Untitled](https://user-images.githubusercontent.com/124760089/217441204-3be44527-1d62-4729-9077-dd5a939c7865.png)

**Comment by YufeiG** [comment]
what version of python are you running?

**Comment by YufeiG** [comment]
try top of main

**Comment by NeauraNightsong** [comment]
I am running Python 3.11
I have to say though I am quite a novice with this and if you could explain your suggestion like you would to a child, that might be more helpful for me, heh.. As I don't understand the suggestion. (I'm sorry!) But I thank you for your response and your time! I also posted in the discord where you pointed me to.

**Comment by YufeiG** [comment]
yeah we're helping you on the discord.

followup here, the command you want to run in the terminal is "python -m src.main"
