### ISSUE TITLE
Additional features suggestions

### ISSUE THREAD

**Issue by Veylkh** [openai/gpt-discord-bot#5]
I've found a few more advanced features that'd be an appreciable addition to those already in place:
- token usage limit per thread (to lower the price-per-answer in long threads and supplement the existing feature of limiting maximum messages per thread)
- token usage count per user (total and for a set period, such as a day or month) to prevent abuse and allow fair usage across users
- ability to store chats and possibly feed it into a custom model fine-tuning (in .JSONL or else)
- per-server variable or per-user prompt or role setting for language selection

**Comment by YufeiG** [comment]
Please fork and implement there. This is example base code.

**Comment by TheButterbrotMan** [comment]
If anyone maybe implents this in a fork, could they share it her, please?

"ability to store chats and possibly feed it into a custom model fine-tuning (in .JSONL or else)"
