### ISSUE TITLE
Bot is strict, how to change moderation?

### ISSUE THREAD

**Issue by dl-tg** [openai/gpt-discord-bot#53]
The chat bot seems to be ridiculiously strict and it gets annoying. Is there a way I could "tone it down"?

**Comment by baba-boota** [comment]
the easiest way would be to I guess. lower the numbers by 10x in constants.py

**Comment by Nekose** [comment]
It looks like there is an error in the documentation. **Raising** the value reduces how strict the moderation is. Setting the values to .99 effectively disables it.

**Comment by Kav-K** [comment]
Yup! @dl-tg Reducing the numbers in constants.py will make moderation for the specified category less strict, with 1.0 being no moderation at all for that category.
