### ISSUE TITLE
How i can add gpt-3.5-turbo to the bot?

### ISSUE THREAD

**Issue by Zensud** [openai/gpt-discord-bot#55]
When I just change the engine to gpt-3.5-turbo in completion.py it just get error like this 
Invalid request - This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions

**Comment by 4mlsx** [comment]
Check pull request 'use chat model'

**Comment by Festival0103** [comment]
@Amalbro07, do you know if there is a need for any other corrections besides filling in Tokens and IDs? I am not sure why it is not working for me. It successfully connects to Discord without any errors, but it does not reply to any messages (using /chat command) and remains completely silent. Unfortunately, I do not know how to properly investigate these types of issues. OpenAI token itself 100% working, as I tested it with basic code.

**Comment by 4mlsx** [comment]
@Festival0103 Did you update the bot into GPT3.5 turbo?

**Comment by Festival0103** [comment]
> Did you update the bot into GPT3.5 turbo?

@Amalbro07 Yes I am. I've used files from pull request that you mentioned above.

**Comment by 4mlsx** [comment]
> > Did you update the bot into GPT3.5 turbo?
> 
> @Amalbro07 Yes I am. I've used files from pull request that you mentioned above.
> 

Did you get any errors?

**Comment by Festival0103** [comment]
> Did you get any errors?

Nah, it's saying that everything is fine and normal, and that it is connected to Discord:
```
2023-04-02 00:40:42 INFO     discord.client logging in using static token
2023-04-02 00:40:43 INFO     discord.gateway Shard ID None has connected to Gateway
```
The bot appears online in Discord but doesn't react to any messages.
My guess is that it fails to communicate with the OpenAI API, but I'm not sure what to do then.

**Comment by Kav-K** [comment]
Hi there, gpt-3.5-turbo is available now
