### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mohdjariullah** [openai/gpt-discord-bot#67]
**Describe the bug**
Syntax error even after syntax is correct

**To Reproduce**
1. Go to '.env file'
2. Click on 'SERVER_TO_MODERATION_CHANNEL'
3. i added server_id : channel_id 

**Expected behavior**
Synatx : Error

**Screenshots**
![image](https://github.com/openai/gpt-discord-bot/assets/112340610/8780be24-7cdf-4d19-bb71-9a6b27d03d70)
**What OS are you running this on? (please complete the following information):**
 Edition	-Windows 10 Pro
Version- 22H2
Installed on-	‎23-‎04-‎2022
OS build-	19045.2965
Experience-	Windows Feature Experience Pack 1000.19041.1000.0

**Additional context**

**Comment by Kav-K** [comment]
Hi there @Mohdjariullah, you need to rename `.env.example` to `.env` firstly, is this the error you get when you run the bot with `python -m src.main`?
