### ISSUE TITLE
bot refuses to start.

### ISSUE THREAD

**Issue by RhysyPiece360** [openai/gpt-discord-bot#9]
Everytime i try and start it using the provided start command
python -m src.main

i just get
/usr/bin/python: No Module Named SRC

**Comment by SaturnCassini** [comment]
getting the same issue when running that line after basic setup

**Comment by gauravnarlawar** [comment]
just move the main.py file from the src folder and paste it in the bot folder. like this.
![image](https://user-images.githubusercontent.com/109208028/210618539-38415584-9ca2-4157-bf66-3a7feeb2e32a.png)

**Comment by SaturnCassini** [comment]
solution on my end

`python3 -m src.py`

if you're on macos or linux for example should work

**Comment by YufeiG** [comment]
ah try running `touch src/__init__.py` and then trying python -m src.main again

**Comment by EMPTYyYyYyY** [comment]
Hi! Can u help, when I try to launch the bot, it gives these errors(
![image](https://user-images.githubusercontent.com/100416774/214582532-33f01767-332c-4436-91c9-dfa7a2ada740.png)

**Comment by RealityMoez** [comment]
check your discord bot token.

**Comment by YufeiG** [comment]
For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757)

**Comment by YufeiG** [comment]
> Everytime i try and start it using the provided start command python -m src.main
> 
> i just get /usr/bin/python: No Module Named SRC

Make sure your python3 is up to date
